#!/bin/bash

jack_connect "Blue Snowball:capture_FL" "voice-gate:in_l"
jack_connect "Blue Snowball:capture_FR" "voice-gate:in_r"

maybe-create-node() {
  type=$1
  name=$2

  case $type in
    duplex)
      class=Audio/Duplex
      ;;
    sink)
      class=Audio/Sink
      ;;
    source)
      class=Audio/Source/Virtual
      ;;
    *)
      echo >&2 "Unknown type: ${type@Q}"
      return 1
      ;;
  esac
  if ! pw-cli dump short Node | grep -q "$name"; then
    pactl load-module module-null-sink sink_name="$name" media.class="$class" channel_map=stereo object.linger=1 device.description="$name"
  fi
}

maybe-create-node sink "mic-and-speakers"
jack_connect "mic-and-speakers:monitor_FL" "HD-Audio Generic:playback_FL"
jack_connect "mic-and-speakers:monitor_FR" "HD-Audio Generic:playback_FR"

maybe-create-node source "mic-mix"
jack_connect "mic-and-speakers:monitor_FL" "mic-mix:input_FL"
jack_connect "mic-and-speakers:monitor_FR" "mic-mix:input_FR"
jack_connect "voice-gate:out_l" "mic-mix:input_FL"
jack_connect "voice-gate:out_r" "mic-mix:input_FR"

pactl set-default-source "mic-mix"
pactl set-source-volume "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201305-00.analog-stereo" 57670
