#!/bin/bash
name=$1
plugin=$2
controls=$3

declare -a control_args
IFS=$',\n' read -rd '' -a split <<<"$controls"
for c in "${split[@]}"; do
  control_args+=(-c "$c")
done

set -x
exec jalv -ix -n "$name" "${control_args[@]}" "$plugin"
