dark_bg = "151919"
dark_brightbg = "202223"
dark_shadow = "000000"
dark_veryfaint = "2b2e31"
dark_faint = "4a4e50"
dark_subtle = "7e8082"
dark_normal = "b7b7b7"
dark_bright = "e4e4e4"
dark_red = "cc554a"
dark_red_dim = "8e322a"
dark_red_bright = "f97e70"
dark_red_hl = "a1584f"
dark_red_bg = "441a15"
dark_orange = "c27324"
dark_orange_dim = "884d0d"
dark_orange_bright = "ee9b52"
dark_orange_hl = "9a693f"
dark_orange_bg = "40260a"
dark_yellow = "ae9829"
dark_yellow_dim = "7c6b18"
dark_yellow_bright = "d8c159"
dark_yellow_hl = "8b8043"
dark_yellow_bg = "39330e"
dark_green = "5b9d2c"
dark_green_dim = "396d0d"
dark_green_bright = "83c758"
dark_green_hl = "588342"
dark_green_bg = "19350c"
dark_cyan = "00a391"
dark_cyan_dim = "007164"
dark_cyan_bright = "49ccba"
dark_cyan_hl = "39867b"
dark_cyan_bg = "003630"
dark_blue = "2b92e1"
dark_blue_dim = "0d64a2"
dark_blue_bright = "5abbff"
dark_blue_hl = "417cae"
dark_blue_bg = "06304e"
dark_violet = "876dda"
dark_violet_dim = "5b469b"
dark_violet_bright = "ae96ff"
dark_violet_hl = "7266a9"
dark_violet_bg = "2a234b"
dark_magenta = "b15ba7"
dark_magenta_dim = "7a3872"
dark_magenta_bright = "dc83d0"
dark_magenta_hl = "8f5b89"
dark_magenta_bg = "3a1c37"
light_bg = "f5f1ed"
light_brightbg = "fcf7f4"
light_shadow = "e6e4e2"
light_veryfaint = "d5ccc5"
light_faint = "a39d98"
light_subtle = "6d6863"
light_normal = "3d3a37"
light_bright = "010000"
light_red = "9f4138"
light_red_dim = "be8981"
light_red_bright = "c25147"
light_red_hl = "ffad9f"
light_red_bg = "f8dad4"
light_orange = "925001"
light_orange_dim = "b59072"
light_orange_bright = "b36300"
light_orange_hl = "ffbb7d"
light_orange_bg = "f2decd"
light_yellow = "857100"
light_yellow_dim = "aca075"
light_yellow_bright = "a18800"
light_yellow_hl = "f4df81"
light_yellow_bg = "eee7d0"
light_green = "477116"
light_green_dim = "8ca176"
light_green_bright = "588b1e"
light_green_hl = "afdf87"
light_green_bg = "dde6cf"
light_cyan = "007265"
light_cyan_dim = "77a197"
light_cyan_bright = "008d7d"
light_cyan_hl = "79e0cf"
light_cyan_bg = "d5e5df"
light_blue = "1568a1"
light_blue_dim = "7c9cb9"
light_blue_bright = "1a80c5"
light_blue_hl = "8ad6ff"
light_blue_bg = "d6e4f0"
light_violet = "6655a0"
light_violet_dim = "9a92b8"
light_violet_bright = "7d69c4"
light_violet_hl = "cfc0ff"
light_violet_bg = "e4dff0"
light_magenta = "894780"
light_magenta_dim = "b08ba7"
light_magenta_bright = "a8589e"
light_magenta_hl = "fbb1f0"
light_magenta_bg = "f0dbe7"
