#!/bin/bash

# Fix horizontal scrolling with touchpad
#synclient HorizScrollDelta=200

# Start Pidgin
if [ `date +%H` -ge 6 ]
then
    pidgin &
fi

nm-applet &

#xbindkeys &
#killall conky; conky &
killall redshift; redshift &
