#!/bin/bash

maybelink() {
    if [[ ! -e $1 ]]; then
        echo "$1 doesn't exist; skipping"
    elif [[ $2 -ef $1 ]]; then
        echo "$2 is already correct; skipping"
    else
        [[ -d $(dirname "$2") ]] || mkdir -p "$(dirname "$2")"
        if [[ -e $2 || -h $2 ]]; then
            echo mv "$2" "$2.old"
            mv "$2" "$2.old"
        fi
        echo ln --symbolic --relative "$1" "$2"
        ln --symbolic --relative "$1" "$2"
    fi
}

maybelink alacritty.yml ~/.config/alacritty/alacritty.yml
maybelink atom-keymap.cson ~/.atom/keymap.cson
maybelink bash_profile ~/.bash_profile
maybelink bashrc ~/.bashrc
maybelink bin ~/bin
maybelink dunstrc ~/.config/dunst/dunstrc
maybelink feh-themes ~/.config/feh/themes
maybelink fonts.conf ~/.config/fontconfig/fonts.conf
maybelink gitconfig ~/.gitconfig
maybelink gtkrc-2.0 ~/.gtkrc-2.0
maybelink gtk-3.0-settings.ini ~/.config/gtk-3.0/settings.ini
maybelink i3config ~/.config/i3/config
maybelink i3statusconfig ~/.config/i3status/config
maybelink inputrc ~/.inputrc
maybelink ipython_config.py ~/.ipython/profile_default/ipython_config.py
maybelink jackdbus.service ~/.config/systemd/user/jackdbus.service
maybelink profile ~/.profile
maybelink pythonrc ~/.pythonrc
maybelink sxhkdrc ~/.config/sxhkd/sxhkdrc
maybelink tmux.conf ~/.tmux.conf
maybelink nvim ~/.vim
maybelink nvim/init.vim ~/.vimrc
maybelink nvim/init.vim ~/.config/nvim/init.vim
maybelink nvim/pack ~/.local/share/nvim/site/pack
maybelink user-dirs.dirs ~/.config/user-dirs.dirs
maybelink update-wallpaper.service ~/.config/systemd/user/update-wallpaper.service
maybelink update-wallpaper.timer ~/.config/systemd/user/update-wallpaper.timer
maybelink Xresources ~/.Xresources

if [[ $(hostname) != colinchan-x1 ]]; then
    maybelink default.pa ~/.config/pulse/default.pa
fi

for app in applications/*; do
    maybelink "$app" ~/.local/share/"$app"
done

echo Run \'git submodule update --init\' to get the vim plugins
