#!/bin/bash

maybelink() {
    if [[ ! -h $2 ]]; then
        echo ln --symbolic --relative --backup --suffix=.old "$1" "$2"
        ln --symbolic --relative --backup --suffix=.old "$1" "$2"
    else
        echo "$2 is already a symlink; skipping"
    fi
}

maybelink bashrc ~/.bashrc
maybelink gitconfig ~/.gitconfig
maybelink gtkrc-2.0 ~/.gtkrc-2.0
maybelink profile ~/.profile
maybelink pythonrc ~/.pythonrc
maybelink tmux.conf ~/.tmux.conf
maybelink vim ~/.vim
maybelink vimrc ~/.vimrc

echo Run \'git submodule update --init\' to update the vim plugins
