#!/bin/sh

rsync --progress --itemize-changes \
      --recursive --times --perms \
      --update --inplace \
      --delete --delete-excluded \
      --exclude christmas/ \
      /home/lumpy/music/audio/ \
      lychee:/var/music/
