#!/usr/bin/env python

import argparse
import collections
import datetime
import itertools
import json
import os
import random
import sys
import unicodedata
import urllib
from collections import Counter, OrderedDict, defaultdict, namedtuple
from contextlib import contextmanager
from datetime import date, datetime, timedelta
from fractions import Fraction
from functools import partial, reduce
from itertools import chain, combinations, count, permutations, product, starmap
from random import choice, sample
from shlex import quote
from urllib.parse import quote as url_quote
from urllib.parse import unquote as url_unquote

if sys.version_info.major > 2:
    from pathlib import Path
else:
    try:
        import readline
    except ImportError:
        print(".pythonrc: Module readline not available.")
    else:
        import rlcompleter

        readline.parse_and_bind("tab: complete")

parser = argparse.ArgumentParser()
