#!/usr/bin/env python

import argparse
import collections
import itertools
import json
import os
import random
import sys
import unicodedata
from collections import Counter, defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, field, fields, asdict
from datetime import date, datetime, timedelta
from decimal import Decimal
from fractions import Fraction
from functools import partial, reduce
from ipaddress import ip_address, ip_network
from itertools import chain, combinations, count, permutations, product, starmap
from pathlib import Path
from random import choice, sample
from shlex import quote
from urllib.parse import quote as urlquote
from urllib.parse import unquote as urlunquote
from urllib.parse import urlencode
