theme = "kalgykai-dark"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 100

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'“' = '”'
'‘' = '’'

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
tab = "all"
