theme = "kalgykai-dark"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 100
insert-final-newline = false
text-width = 100

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'“' = '”'
'‘' = '’'

[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
newline = "all"
tab = "all"

[keys.normal]
"X" = "extend_line_above"

[keys.insert]
"C-[" = "normal_mode"

[keys.normal.space]
"o" = ":reflow"
