"attribute" = "cyan"
"comment" = { fg = "subtle", modifiers = ["italic"] }
"constant" = "blue"
"constant.character" = "yellow"
"constant.character.escape" = { fg = "orange", modifiers = ["italic"] }
"function" = "green"
"function.macro" = "violet"
"function.special" = "violet"
"keyword" = { fg = "subtle", modifiers = ["bold"] }
"label" = "cyan"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "orange"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.label" = "blue"
"operator" = "subtle"
"punctuation" = "subtle"
"string" = "yellow"
"tag" = "green"
"type" = "cyan"
"variable.builtin" = { modifiers = ["bold"] }
"variable.parameter" = "subtle"

"hint" = "bright-cyan"
"info" = "bright-blue"
"warning" = "bright-violet"
"error" = "bright-magenta"
"diagnostic.hint" = { underline = { color = "bright-cyan" } }
"diagnostic.info" = { underline = { color = "bright-blue" } }
"diagnostic.warning" = { underline = { color = "bright-violet", style = "curl" } }
"diagnostic.error" = { underline = { color = "bright-magenta", style = "curl" } }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "orange"

"ui.cursor" = { bg = "subtle" }
"ui.cursor.match" = { fg = "bright-orange" }
"ui.cursor.primary" = { fg = "bg", bg = "bright-normal" }
"ui.cursor.primary.insert" = { fg = "bg", bg = "bright-green" }
"ui.cursor.primary.select" = { fg = "bg", bg = "bright-cyan" }
"ui.cursorline.primary" = { bg = "bright-bg" }
"ui.linenr" = "dark"
"ui.linenr.selected" = { fg = "dark", modifiers = ["bold"] }
"ui.selection" = { bg = "hl-grey" }
"ui.selection.primary" = { fg = "bg", bg = "normal" }
"ui.statusline" = { fg = "bright-normal", bg = "dark", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "subtle", bg = "bright-bg" }
"ui.statusline.normal" = { fg = "shadow", bg = "bright-normal", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "shadow", bg = "bright-green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "shadow", bg = "bright-cyan", modifiers = ["bold"] }
"ui.text" = "normal"
"ui.virtual" = { fg = "verydark" }
"ui.virtual.inlay-hint" = { fg = "dark", modifiers = ["italic"] }
"ui.virtual.ruler" = { bg = "bright-bg" }
"ui.window" = { fg = "dark" }  # border between windows

# Command line
"ui.help" = { fg = "bright-blue", bg = "bright-bg" }
"ui.menu" = { fg = "blue", bg = "bright-bg" }
"ui.menu.selected" = { fg = "bg", bg = "blue" }
"ui.text.inactive" = { fg = "subtle" }

# File picker
"ui.background" = { fg = "subtle", bg = "bg" }
"ui.text.focus" = { fg = "shadow", bg = "green", modifiers = ["bold"] }
"special" = { underline = { style = "line" } }  # matching characters in file picker
"ui.highlight" = { bg = "hl-grey" }  # highlight on lines containing reference

# Keybinding help popup
"ui.popup" = { fg = "bright-blue", bg = "bright-bg" }
"ui.text.info" = { fg = "bright-blue" }

"note" = { fg = "bright-orange" }
"todo" = { fg = "bright-red" }

[palette]
shadow = "#000000"
bg = "#f4f4f4"
bright-bg = "#fafafa"
verydark = "#d0d0d0"
dark = "#a0a0a0"
subtle = "#707070"
normal = "#404040"
red = "#c8514d"
orange = "#b86c00"
yellow = "#9b8700"
green = "#3f8f2b"
cyan = "#00967e"
blue = "#0083cc"
violet = "#8363cc"
magenta = "#ac52a6"
bright-normal = "#514d43"
bright-red = "#e05a55"
bright-orange = "#cf7800"
bright-yellow = "#ad9600"
bright-green = "#46a02e"
bright-cyan = "#00a88d"
bright-blue = "#0093e6"
bright-violet = "#936fe5"
bright-magenta = "#c15bba"
bg-red = "#ffe5e1"
bg-orange = "#ffecd5"
bg-yellow = "#f9f4d7"
bg-green = "#dff7d9"
bg-cyan = "#daf9f0"
bg-blue = "#d8f4ff"
bg-violet = "#f1e9ff"
bg-magenta = "#ffe4fe"
hl-normal = "#929292"
hl-yellow = "#d3c687"
hl-cyan = "#8dd1bf"
