"attribute" = "cyan"
"comment" = { fg = "subtle", modifiers = ["italic"] }
"constant" = "blue"
"constant.character" = "yellow"
"constant.character.escape" = { fg = "orange", modifiers = ["italic"] }
"function" = "green"
"function.macro" = "violet"
"function.special" = "violet"
"keyword" = { fg = "subtle", modifiers = ["bold"] }
"label" = "cyan"
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = "orange"
"markup.italic" = { modifiers = ["italic"] }
"markup.link.label" = "blue"
"operator" = "subtle"
"punctuation" = "subtle"
"string" = "yellow"
"tag" = "green"
"type" = "cyan"
"variable" = "normal"
"variable.builtin" = { fg = "subtle", modifiers = ["bold"] }
"variable.parameter" = "subtle"

"hint" = "bright-cyan"
"info" = "bright-blue"
"warning" = "bright-violet"
"error" = "bright-magenta"
"diagnostic.hint" = { underline = { color = "bright-cyan" } }
"diagnostic.info" = { underline = { color = "bright-blue" } }
"diagnostic.warning" = { underline = { color = "bright-violet", style = "curl" } }
"diagnostic.error" = { underline = { color = "bright-magenta", style = "curl" } }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "orange"

"ui.bufferline" = { fg = "subtle", bg = "veryfaint" }
"ui.bufferline.active" = { fg = "normal", bg = "bright-bg", modifiers = ["bold"] }
"ui.cursor" = { bg = "subtle" }
"ui.cursor.match" = { fg = "bright-orange" }
"ui.cursor.primary" = { fg = "bg", bg = "normal" }
"ui.cursor.primary.insert" = { fg = "bg", bg = "bright-green" }
"ui.cursor.primary.select" = { fg = "bg", bg = "bright-cyan" }
"ui.cursorline.primary" = { bg = "bright-bg" }
"ui.linenr" = "faint"
"ui.linenr.selected" = { fg = "faint", modifiers = ["bold"] }
"ui.selection" = { bg = "hl-grey" }
"ui.selection.primary" = { fg = "bg", bg = "subtle" }
"ui.statusline" = { fg = "normal", bg = "faint", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "subtle", bg = "bright-bg" }
"ui.statusline.normal" = { fg = "bg", bg = "normal", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg", bg = "bright-green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg", bg = "bright-cyan", modifiers = ["bold"] }
"ui.text" = "normal"
"ui.virtual" = { fg = "veryfaint" }
"ui.virtual.inlay-hint" = { fg = "faint", modifiers = ["italic"] }
"ui.virtual.ruler" = { bg = "bright-bg" }
"ui.window" = { fg = "faint" }  # border between windows

# Command line
"ui.help" = { fg = "bright-blue", bg = "bright-bg" }
"ui.menu" = { fg = "blue", bg = "bright-bg" }
"ui.menu.selected" = { fg = "bg", bg = "blue" }
"ui.text.inactive" = { fg = "subtle" }

# File picker
"ui.background" = { fg = "subtle", bg = "bg" }
"ui.text.focus" = { fg = "bg", bg = "green", modifiers = ["bold"] }
"special" = { underline = { style = "line" } }  # matching characters in file picker
"ui.highlight" = { bg = "hl-grey" }  # highlight on lines containing reference

# Keybinding help popup
"ui.popup" = { fg = "bright-blue", bg = "bright-bg" }
"ui.text.info" = { fg = "bright-blue" }

"note" = { fg = "bright-orange" }
"todo" = { fg = "bright-red" }

[palette]
bg = "#ebe7e3"
bright-bg = "#f2edea"
shadow = "#e1ddda"
veryfaint = "#d1cdc9"
faint = "#b1adaa"
subtle = "#837f7c"
normal = "#3d3a37"
bright = "#040302"
red = "#ca625e"
orange = "#bd7119"
yellow = "#9c8600"
green = "#5b9845"
cyan = "#009f91"
blue = "#2d8dd0"
violet = "#8d74cd"
magenta = "#b166ad"
bright-red = "#ef736f"
bright-orange = "#e08619"
bright-yellow = "#b89e00"
bright-green = "#6bb450"
bright-cyan = "#00bcab"
bright-blue = "#33a6f6"
bright-violet = "#a689f3"
bright-magenta = "#d179cd"
bg-red = "#f1cfca"
bg-orange = "#ecd3be"
bg-yellow = "#e0d8bc"
bg-green = "#d0ddc5"
bg-cyan = "#c2e0d8"
bg-blue = "#c8dbeb"
bg-violet = "#dcd4eb"
bg-magenta = "#e8d0e1"
hl-grey = "#a0a0a0"
hl-normal = "#929292"
hl-yellow = "#d5c685"
hl-cyan = "#87d7cb"
