#!/bin/sh

rsync --progress --itemize-changes \
      --recursive --perms \
      --inplace --checksum \
      --delete --delete-excluded \
      /home/lumpy/music/audio/ \
      fruitron:/var/zachary/music/
