#!/bin/sh

rsync \
      "$@" \
      --delete \
      --itemize-changes \
      --partial \
      --perms \
      --progress \
      --recursive \
      --times \
      /home/lumpy/music/audio/ \
      lemon:/home/share/music/
