#!/bin/sh

#EXCLUDE="--exclude christmas"

for dry in --dry-run ''; do
    echo ">> Running: rsync $dry"
    rsync $dry \
          --progress --itemize-changes \
          --recursive --perms \
          --inplace --checksum \
          --delete --delete-excluded \
          $EXCLUDE \
          /home/lumpy/music/audio/ \
          lychee:/var/music/
done
