#!/bin/sh

# Enable whatever monitors are connected
xrandr \
    --output HDMI1 --auto --pos 1366x0 \
    --output LVDS1 --auto --pos 0x312 \
    --output VGA1 --auto --same-as LVDS1

# Reset the wallpaper
feh --bg-fill /home/share/wallpaper_1920x1080.png

# Reset the keyboard repeat and enable numlock
xset r rate 160 40
numlockx
