#!/bin/sh

# Enable whatever monitors are connected
#xrandr \
#    --output HDMI1 --auto --pos 0x0 \
#    --output LVDS1 --auto --pos 1400x1080 \
#    --output VGA1 --auto --same-as LVDS1
xrandr \
    --output HDMI1 --auto --pos 0x0 \
    --output LVDS1 --auto --pos 1920x420 \
    --output VGA1 --auto --same-as LVDS1

# Reset the wallpaper
feh --bg-fill /home/share/wallpaper_1920x1080.png

# Start redshift if it isn't running already
pgrep redshift || redshift -l 29.65:-82.35 -t 5800:3000 -b 1.0:0.8 &

# Reset the keyboard repeat and enable numlock
xset r rate 160 40
numlockx
