#!/bin/bash

if (( $# != 1 )); then
    echo "usage: $0 SOUND_NAME"
    exit 1
fi

SOUNDS_DIR=/home/lumpy/sounds

declare -A soundfiles
soundfiles=(
    ["bam"]=$SOUNDS_DIR/recordings/effects/bam.flac
    ["buzzer"]=$SOUNDS_DIR/system/delete.wav
    ["bye"]=$SOUNDS_DIR/Zelda/WW_Beedle_Bye.wav
    ["ding"]=$SOUNDS_DIR/265012__sethlind__toaster-oven-ding.wav
    ["ffkkqshhhp"]=$SOUNDS_DIR/recordings/effects/ffkkqshhhp.flac
    ["kabooooooooom_psshsshshshsh_erm"]=$SOUNDS_DIR/recordings/effects/kabooooooooom_psshsshshshsh_erm.flac
    ["mac"]=$SOUNDS_DIR/mac.wav
    ["nnnnnnywww"]=$SOUNDS_DIR/recordings/effects/nnnnnnywww.flac
    ["ohhh"]=$SOUNDS_DIR/Zelda/WW_Beedle_Ohhh.wav
    ["short_buzzer"]=$SOUNDS_DIR/system/short_buzzer.wav
    ["secret"]=$SOUNDS_DIR/Zelda/Oracle_Secret.wav
    ["soup"]=$SOUNDS_DIR/recordings/effects/soup.flac
)

echo paplay "${soundfiles[$1]}"
paplay "${soundfiles[$1]}"
