#!/bin/sh

# Enable whatever monitors are connected
#xrandr \
#    --output HDMI1 --auto --pos 0x0 \
#    --output LVDS1 --auto --pos 1400x1080 \
#    --output VGA1 --auto --same-as LVDS1
xrandr \
    --output eDP1 --auto --pos 0x1000 \
    --output DP1-8 --auto --pos 2560x0 \
    --output HDMI1 --auto --same-as eDP1

# Reset the wallpaper
feh --bg-fill /home/colinchan/pictures/wallpapers/Facebook_Backgrounds--node_world.png

# Start redshift if it isn't running already
pgrep redshift || redshift -l 37.42:-122.20 -t 5800:2800 -b 1.0:0.8 &

# Reset the keyboard repeat and enable numlock
xset r rate 160 40
numlockx
