#!/bin/bash

colinishome=$(curl -s "http://fence.lumeh.org/colin/ishome")
if [[ $colinishome == False ]]; then
    echo "skipping because Colin isn't home..." >&2
    exit
fi

MPC='mpc'
BEDTIME_VOLUME=40
BEDTIME_CROSSFADE=8
LATE_START_TIME=$(((22 * 60 + 38) * 60))

echo "starting to schedule for bedtime..." >&2

remaining_time=$($MPC | grep playing |
                 awk -F ':|/| +' '{ print ($6 * 60 + $7) - ($4 * 60 + $5) }')
if [[ $remaining_time -lt 0 ]]; then
    remaining_time=9001
fi

# Disable repeat
$MPC repeat off >/dev/null

# Enable bedtime crossfade
$MPC crossfade $BEDTIME_CROSSFADE >/dev/null

# Queue the songs
last_song_position=$($MPC playlist | wc -l)
$MPC ls bedtime | sort | $MPC add >/dev/null

if $MPC | grep -q playing; then
    current_time=$(date +'%H %M %S' | awk '{ print ($1 * 60 + $2) * 60 + $3 }')

    if [[ $(($current_time + $remaining_time)) -lt $LATE_START_TIME ]]; then
        echo "queueing songs for later..." >&2

        # Move the current playing song to just before the bedtime songs
        $MPC move $($MPC -f %position% | head -n 1) $last_song_position >/dev/null

        # Wait until Nemo ends
        $MPC current --wait >/dev/null
        $MPC current --wait >/dev/null

    else
        echo "current song is too long. fading out..." >&2

        # Fade out current song
        volume=$($MPC volume | cut -d ' ' -f 2 | sed 's/%//')
        newvolume=$volume
        while [ $newvolume -gt 0 ]; do
            sleep 0.4
            $MPC volume $newvolume >/dev/null
            newvolume=$(($newvolume - 3))
        done
        $MPC stop >/dev/null
        $MPC volume $volume >/dev/null

        # Start with Papillon
        $MPC play $(($last_song_position + 2)) >/dev/null

    fi

else
    echo "starting to play now..." >&2

    $MPC volume $BEDTIME_VOLUME >/dev/null
    $MPC play $(($last_song_position + 1)) >/dev/null

    # Wait until Nemo ends
    $MPC current --wait >/dev/null
fi

# Wait a bit and then reset the crossfading
sleep $BEDTIME_CROSSFADE
$MPC crossfade 0 >/dev/null

# Reset the volume after Papillon ends
$MPC current --wait >/dev/null
$MPC volume $BEDTIME_VOLUME >/dev/null

echo "waiting until it's all done..." >&2
while $MPC status | grep 'playing'; do
    sleep 30
done
echo "done." >&2
